spring:
  datasource:
    url: jdbc:postgresql://db/bank-db
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
  application:
    name: demo
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
    expirationsMs: 86400000